---
- name: Install Kubernetes 1.7.7 with Kubeadmin
  yum:
    name: "{{item}}"
    enablerepo: kubernetes
    state: present
  with_items:
  - kubelet-0:1.7.7-1.x86_64
  - kubeadm-0:1.7.7-1.x86_64
  
- name: "Start and enable Kubelet service"
  service: name={{item}} state=started enabled=yes
  with_items:
    - kubelet
  
